help_msg='''
          systemTColor + "[Available Commands]:" + resetTColor)
            "  Memory Commands:"
            "    /memory - Show memory statistics and recent entries"
            "    /summarize - Create embeddings from recent conversations"
            "    /clear_memory - Clear personal memory (keeps base knowledge)"
            "    /reload_base - Reload base memory files"
            "    /export_memory <file> - Export memory to file"
            "    /import_memory <file> - Import memory from file"
            "    /search_memory <query> - Search personal and base memory"
            "    /search_base <query> - Search only base knowledge"
            "    /memory_stats - Show detailed memory statistics"
            "  Warudo Commands:"
            "    /warudo_connect - Connect to Warudo WebSocket"
            "    /warudo_test - Test Warudo connection with sample animations"
            "    /warudo_commands - Show available Warudo commands"
            "    /warudo_send <command> - Send specific command to Warudo"
            "    /warudo_keywords - Show animation keyword mappings"
            "  Mindcraft Commands:"
            "    /minecraft_test - Test connection to Minecraft bot"
            "    /minecraft_status - Check Minecraft bot status"
            "    /minecraft_action <action> - Send specific action to Minecraft bot"
            "    /help - Show this help message"
'''